# tmail docker file

FROM ubuntu
MAINTAINER Groupe 8

# Installation de tmail
apt-get install unzip
USER tmail

WORKDIR /home/tmail/dist/

RUN . conf/tmail.cfg && \
    ./tmail user add -r tmail tmailpasswd

EXPOSE 2525

CMD ["/home/tmail/dist/run"]

. /home/tmail/dist/conf/tmail.cfg

#--------------------------------------------------------------------------------


# Installation de dovecot pour IMAP et POP
apt-get install dovecot-imapd dovecot-pop3d

# Installation de dovecot-mysql, parce qu'on utilise MySQL
apt-get install dovecot-mysql

#--------------------------------------------------------------------------------

