# tmail docker file

FROM toorop/tmail
MAINTAINER Groupe 8

USER tmail

WORKDIR /home/tmail/dist/

RUN . conf/tmail.cfg && \
    ./tmail user add -r tmail tmailpasswd

EXPOSE 2525

CMD ["/home/tmail/dist/run"]
#--------------------------------------------------------------------------------
FROM ubuntu

apt-get install unzip

adduser tmail

# Installation de dovecot pour IMAP et POP
apt-get install dovecot-imapd dovecot-pop3d

# Installation de dovecot-mysql, parce qu'on utilise MySQL
apt-get install dovecot-mysql

#--------------------------------------------------------------------------------

